Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,400]
	 [[{{node input_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "main.py", line 97, in denoise
    mode.test(filename, model=encoder, sess=sess, reset=True, reset_op=reset_op, session_list=session_list)
  File "/home/alg/alg/wdd/Noise_Suppression/Speech_noise_reduction_model.py", line 386, in test
    output_data = sess.run(session_list[1], feed_dict={model.input: input_spec_data[:, i * blockshift:i * blockshift + blockLen]})[0]
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,400]
	 [[node input_1 (defined at /home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'input_1':
  File "main.py", line 139, in <module>
    win.mainloop()
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "main.py", line 92, in denoise
    _, encoder, session_list, reset_op = mode.rnn_encoder()
  File "/home/alg/alg/wdd/Noise_Suppression/Speech_noise_reduction_model.py", line 246, in rnn_encoder
    Encoder_input = Input(batch_shape=(1, 400))
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 265, in Input
    input_layer = InputLayer(**input_layer_config)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 126, in __init__
    ragged=ragged)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 1051, in placeholder
    x = array_ops.placeholder(dtype, shape=shape, name=name)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/alg/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

